export interface Project {
    proyectoGuid: string;
    nombre: string;
    comercial?: string;
    propietarioProyecto?: string;
    estado?: string;
    [key: string]: any;
}

export interface ActivityPayload {
    titulo: string;
    horas: number;
    observacion: string;
    fecharegistro: string; // YYYY-MM-DD

    // New fields required by backend
    GuidProyect: string;
    cliente: string;
    comercial: string;
    areaInterna: string;
    estado: string; // "Pendiente"
    guid: string; // Assuming this is generated by frontend or passed? User sample has one.
    otro: string;
    subAreas: string;
    areaSolicitante: string;
    numeroTicket: string;
    descripcionRequerimiento: string;
    tipoActividad: string;
    rutaSoportes: string;
    tipoHora: string;
    equipos: string;
}

export interface AIResponse {
    titulo: string | null;
    horas: number | null;
    observacion: string | null;
    fecharegistro: string | null;
}
